stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    # This job now runs on pushes to EITHER branch
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'

# Job for deploying to the DEV server
deploy_to_dev:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client docker-compose
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh idtc@$SERVER_IP "
        set -e;
        echo 'Deploying to DEV Server';
        cd /srv/moodle/dev;
        echo '1. Updating Image Tag in dev compose.yml';
        sed -i 's|image: moodlehq/moodle-php-apache:.*|image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}|g' compose.yml;
        echo '2. Pulling the new image and restarting';
        docker compose pull;
        docker compose up -d;
        echo '3. Running Moodle database upgrade for DEV';
        sleep 30;
        docker compose exec -u www-data moodle-app php /var/www/html/admin/cli/upgrade.php --non-interactive;
        echo '4. Purging Moodle caches for DEV';
        docker compose exec -u www-data moodle-app php /var/www/html/admin/cli/purge_caches.php;
        echo 'Deployment to DEV finished!';
      "
  rules:
    # This job only runs on pushes to the 'develop' branch
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Job for deploying to the QAS server
deploy_to_qas:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client docker-compose
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh idtc@$SERVER_IP "
        set -e;
        echo 'Deploying to QAS Server';
        cd /srv/moodle/qas;
        echo '1. Updating Image Tag in qas compose.yml';
        sed -i 's|image: bitnami/moodle:.*|image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}|g' compose.yml;
        echo '2. Pulling the new image and restarting';
        docker compose pull;
        docker compose up -d;
        echo '3. Running Moodle database upgrade for QAS';
        sleep 30;
        docker compose exec -u daemon moodle-qas php /bitnami/moodle/admin/cli/upgrade.php --non-interactive;
        echo '4. Purging Moodle caches for QAS';
        docker compose exec -u daemon moodle-qas php /bitnami/moodle/admin/cli/purge_caches.php;
        echo 'Deployment to QAS finished!';
      "
  rules:
    # This job now only runs on pushes to the 'main' branch
    - if: '$CI_COMMIT_BRANCH == "main"'