name: Build and Deploy to Server

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  deploy_to_dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: idtc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /srv/moodle/dev
            docker compose pull
            docker compose up -d
            docker compose ps

  deploy_to_qas:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QAS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: idtc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /srv/moodle/qas
            docker compose pull
            docker compose up -d
            docker compose ps
